import { Clock3, Facebook, Mail, MapPin, MessageCircle, Navigation, Phone } from "lucide-react";
import { createMetadata } from "@/lib/seo";

export const metadata = createMetadata({ title: "ติดต่อเรา", description: "ช่องทางติดต่อ ที่อยู่ เวลาทำการ โทรศัพท์ LINE และแผนที่ของอยู่เย็นเป็นสุข วิศวกรรม", path: "/contact" });
import { isGoogleMapsEmbedUrl } from "@/lib/maps";
import { companyPublicConfig as fallback } from "@/lib/public-config";
import { PublicContentService } from "@/server/services/public-content.service";

export default async function ContactPage() {
  const record = await new PublicContentService().getCompany(); const company = { name: record?.displayName ?? fallback.name, phoneDisplay: record?.phoneDisplay ?? fallback.phoneDisplay, phoneHref: record?.phoneHref ?? fallback.phoneHref, lineLabel: record?.lineLabel ?? fallback.lineLabel, lineUrl: record?.lineUrl ?? fallback.lineUrl, email: record?.email ?? fallback.email, facebookUrl: record?.facebookUrl ?? fallback.facebookUrl, mapsUrl: record?.mapsUrl ?? fallback.mapsUrl, mapsEmbedUrl: record?.mapsEmbedUrl ?? fallback.mapsEmbedUrl, address: record?.address ?? fallback.address, businessHours: record?.businessHours ?? fallback.businessHours, isPlaceholder: !record };
  const contacts = [{ icon: Phone, title: "โทรศัพท์", text: company.phoneDisplay, note: "แตะเพื่อโทรหาเรา" }, { icon: MessageCircle, title: "LINE Official", text: company.lineLabel, note: "เพิ่มเพื่อนและเริ่มแชท" }, { icon: Mail, title: "อีเมล", text: company.email, note: "สำหรับติดต่อเรื่องทั่วไป" }, { icon: Clock3, title: "เวลาทำการ", text: company.businessHours, note: "กรุณาติดต่อล่วงหน้า" }];
  return <><section className="page-hero"><div className="container"><p className="eyebrow">CONTACT US</p><h1 className="display">ติดต่อเรา</h1><p className="lead">พูดคุยกับทีมงานเพื่อสอบถามข้อมูลสินค้า บริการ หรือขอคำแนะนำเบื้องต้น</p></div></section><section className="section"><div className="container"><div className="grid-2"><div><div className="grid-2">{contacts.map(item => <article className="card card-body" key={item.title}><span className="icon-box"><item.icon size={22} /></span><p className="eyebrow" style={{ marginTop: 22 }}>{item.title}</p><h2 className="subheading">{item.text}</h2><p className="muted">{item.note}</p></article>)}</div><div className="cluster" style={{ marginTop: 24 }}><a className="btn btn-primary" href={`tel:${company.phoneHref}`}><Phone size={17} /> โทรหาเรา</a>{company.lineUrl ? <a className="btn btn-outline" href={company.lineUrl} target="_blank" rel="noreferrer"><MessageCircle size={17} /> แชทผ่าน LINE</a> : <span className="btn pending-contact" title="รอเจ้าของบริษัทยืนยัน URL"><MessageCircle size={17} /> LINE รอยืนยัน</span>}{company.facebookUrl ? <a className="btn btn-ghost" href={company.facebookUrl} target="_blank" rel="noreferrer"><Facebook size={17} /> Facebook</a> : <span className="btn pending-contact" title="รอเจ้าของบริษัทยืนยัน URL"><Facebook size={17} /> Facebook รอยืนยัน</span>}</div></div><div className="card" style={{ minHeight: 480, background: "#dce7e1", display: "grid", placeItems: "center" }}>{isGoogleMapsEmbedUrl(company.mapsEmbedUrl) ? <iframe className="map-frame" src={company.mapsEmbedUrl} title="แผนที่บริษัท อยู่เย็นเป็นสุข วิศวกรรม" loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen /> : <div style={{ textAlign: "center", padding: 28 }}><MapPin size={42} color="var(--green-700)" /><h2 className="subheading" style={{ marginTop: 15 }}>แผนที่ Google Maps</h2><p className="muted">รอเจ้าของบริษัทยืนยันตำแหน่งและ Embed URL</p>{company.mapsUrl ? <a className="btn btn-dark" href={company.mapsUrl} target="_blank" rel="noreferrer"><Navigation size={17} /> เปิดเส้นทาง</a> : <span className="btn pending-contact"><Navigation size={17} /> ตำแหน่งรอยืนยัน</span>}</div>}</div></div><div className="card card-body" style={{ marginTop: 28 }}><p className="eyebrow">OFFICE ADDRESS</p><h2 className="subheading">{company.name}</h2><p className="lead"><MapPin size={19} style={{ display: "inline", verticalAlign: "middle" }} /> {company.address ?? "ที่อยู่บริษัทจะแสดงหลังเจ้าของบริษัทยืนยันข้อมูลเรียบร้อย"}</p>{company.isPlaceholder && <span className="status draft">ข้อมูลตัวอย่าง — ห้ามเผยแพร่จริง</span>}</div></div></section></>;
}
