/**
 * หน้าที่ของไฟล์นี้: API /api/admin/trash รองรับ GET; ตรวจสอบคำขอ เรียกกฎฝั่งเซิร์ฟเวอร์ และส่งผลลัพธ์ JSON โดยไม่เปิดเผยข้อมูลภายใน
 *
 * หมายเหตุสำหรับผู้อ่านที่ไม่เขียนโค้ด: อ่านคำอธิบายนี้ก่อน แล้วไล่ดูชื่อฟังก์ชันและคอมเมนต์ใกล้กฎสำคัญด้านล่าง
 */
import { NextResponse } from "next/server";
import { db } from "@/server/db";
import { cmsSession } from "@/server/cms/http";
/** จุดเริ่มของคำขอ HTTP GET: อ่านข้อมูลโดยไม่แก้ไขข้อมูล และคืนสถานะที่เหมาะสมให้ผู้เรียก */
export async function GET() { const session = await cmsSession(); if (!session) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const select = { id: true, title: true, deletedAt: true, purgeAt: true } as const; const [banners, services, products, projects, news, brands, types, categories, admins] = await db.$transaction([db.banner.findMany({ where: { deletedAt: { not: null } }, select, orderBy: { deletedAt: "desc" } }), db.service.findMany({ where: { deletedAt: { not: null } }, select, orderBy: { deletedAt: "desc" } }), db.product.findMany({ where: { deletedAt: { not: null } }, select: { id: true, name: true, deletedAt: true, purgeAt: true }, orderBy: { deletedAt: "desc" } }), db.project.findMany({ where: { deletedAt: { not: null } }, select, orderBy: { deletedAt: "desc" } }), db.news.findMany({ where: { deletedAt: { not: null } }, select, orderBy: { deletedAt: "desc" } }), db.brand.findMany({ where: { deletedAt: { not: null } } }), db.productType.findMany({ where: { deletedAt: { not: null } } }), db.newsCategory.findMany({ where: { deletedAt: { not: null } } }), db.admin.findMany({ where: { deletedAt: { not: null }, purgeAt: { not: null }, ...(session.admin.role === "SUPER_ADMIN" ? {} : { id: "" }) }, select: { id: true, displayName: true, username: true, deletedAt: true, purgeAt: true }, orderBy: { deletedAt: "desc" } })]); return NextResponse.json({ role: session.admin.role, items: [...banners.map(item => ({ ...item, kind: "banners" })), ...services.map(item => ({ ...item, kind: "services" })), ...products.map(item => ({ ...item, title: item.name, kind: "products" })), ...projects.map(item => ({ ...item, kind: "projects" })), ...news.map(item => ({ ...item, kind: "news" })), ...brands.map(item => ({ ...item, title: item.name, kind: "brands" })), ...types.map(item => ({ ...item, title: item.name, kind: "product-types" })), ...categories.map(item => ({ ...item, title: item.name, kind: "news-categories" })), ...admins.map(item => ({ ...item, title: `${item.displayName} (${item.username})`, kind: "admins" }))].sort((a, b) => (b.deletedAt?.getTime() ?? 0) - (a.deletedAt?.getTime() ?? 0)) }); }
